import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import SideNav from '@/app/ui/main/sidenav';
import UpperNav from '@/app/ui/main/uppernav';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tavern Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased text-black bg-slate-200`}>
        {children}
      </body>
    </html>
  );
}