version: '3.8'

services:
  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tavern-board
    ports:
      - "3306:3306"
    networks:
      - net
    volumes:
      - ./docker/mysql:/var/lib/mysql

  php:
    image: php:8.3-fpm
    ports:
      - '9000:9000'
    networks:
      - net
    volumes:
      - ./symfony:/var/www/symfony
      
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - net
    volumes:
      - ./symfony:/var/www/symfony

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./front:/var/www/front
    ports:
      - 3000:3000
    networks:
      - net
      
networks:
  net:
    driver: bridge